#!/bin/sh
set -e

# Define the path for the crontab file for the root user
CRONTAB_FILE="/etc/crontabs/root"
LOG_DIR="/var/log/borgmatic"
LOG_FILE="${LOG_DIR}/cron.log"

# --- Cron Schedule Configuration ---
# Use environment variables or set defaults
# Default: Run daily at midnight (00:00)
CRON_MINUTE="${CRON_MINUTE:-0}"
CRON_HOUR="${CRON_HOUR:-0}"
CRON_DOM="${CRON_DOM:-*}"  # Day of Month
CRON_MONTH="${CRON_MONTH:-*}" # Month
CRON_DOW="${CRON_DOW:-*}"  # Day of Week

# --- Cron Command Configuration ---
# Default command: Create a backup with stats, verbosity 1
CRON_COMMAND="${CRON_COMMAND:-borgmatic create --stats -v 1}"

# Ensure the log directory exists
mkdir -p "$LOG_DIR"
touch "$LOG_FILE" # Ensure the log file exists for redirection

# Construct the cron schedule string
CRON_SCHEDULE="$CRON_MINUTE $CRON_HOUR $CRON_DOM $CRON_MONTH $CRON_DOW"

echo "Writing crontab entry to $CRONTAB_FILE"
echo "Schedule: $CRON_SCHEDULE"
echo "Command: $CRON_COMMAND"
echo "Log File: $LOG_FILE"

# Write the crontab entry
# Note: Crontab requires a newline at the end of the file
cat <<EOF > "$CRONTAB_FILE"
# Borgmatic backup schedule (generated by write-crontab.sh)
$CRON_SCHEDULE $CRON_COMMAND >> $LOG_FILE 2>&1

EOF
# The empty line above is important for crond

echo "Crontab written successfully to $CRONTAB_FILE."

# Optional: Display the crontab content for verification
echo "Current crontab content:"
cat "$CRONTAB_FILE"